version: 2.2.{build}

branches:
   only:
     - master    
     
image:
  - Visual Studio 2019
  - Ubuntu      
  
build_script:
  - cmd: Scripts\build_ci_win.cmd
  - sh: 
  - sh: test -d ./build && echo "build exists" || mkdir build
  - sh: cd build
  - sh: cmake ..
  - sh: cmake --build ./ --target Broker
  - sh: cmake --build ./ --target Launcher
