version: 2.2.{build}

branches:
   only:
     - master    
     
image:
  - Visual Studio 2019
  - Ubuntu      
  
build_script:
  - cmd: Scripts\build_ci_win.cmd
  - sh: 
    test -d ./build && echo "build exists" || mkdir build
    cd build
    cmake ..
    cmake --build ./ --target Broker
    cmake --build ./ --target Launcher
